services:
  mc:
    build: .
    environment:
      - EULA=true
      - VERSION=1.20.1
      - TYPE=AUTO_CURSEFORGE
      - SEED=31563250179158
      - CF_MODPACK_MANIFEST=/mods/manifest.json
      - CF_SLUG="E.K.I.P"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - mods:/mods
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}