services:
  mc:
    build: .
    environment:
      - EULA=true
      - VERSION=1.20.1
      - TYPE=FORGE
      - SEED=31563250179158
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - mods:/mods
      - config:/config
      - resourcepacks:/resourcepacks
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}