services:
  mc:
    build: .
    environment:
      - EULA=true
      - VERSION=1.20.1
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}