services:
  mc:
    build: .
    environment:
      - EULA=true
      - VERSION=1.20.1
      - TYPE=FORGE
      - SEED=31563250179158
      - REMOVE_OLD_MODS=true
      - ONLINE_MODE=false
      - MAX_MEMORY=3G
      - DEBUG=true
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./mods:/mods
      # - ./config:/config
      - ./resourcepacks:/resourcepacks
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}